version: '3.5'

services:
  msemployer:
    image: msemployer-image
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=9000
        - traefik.frontend.rule=Host:employer.services.alin.be
        - traefik.frontend.entryPoints=http,https
        - traefik.backend.loadbalancer.method=wrr
    depends_on:
      - dbEmployer
    environment:
     - spring.datasource.url=jdbc:mariadb://dbEmployer/employer
     - spring.metrics.export.statsd.host=localhost
     - spring.metrics.export.statsd.port=7017
     - spf.cors=http://doc.services.alin.be
    entrypoint: java -jar /opt/employer-rest-0.1.0.jar

  dbEmployer:
    image: mariadb:10.3.4
    environment:
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=employer
    volumes:
     - ./datadir:/var/lib/mysql

networks:
  default:
    external:
      name: traefik-net
